name: container
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Build
      run: C:\tools\msys64\usr\bin\bash -lc "cd $GITHUB_WORKSPACE && ./ci/cerbero_setup.sh cerbero_script"