name: container
on: push

jobs:
  build:
    runs-on: windows-latest
    container:
      image: registry.freedesktop.org/gstreamer/gstreamer/amd64/windows:2021-10-01.0-master
    steps:
         - name: Log the node version
           run: |
              - python --version
